services:
  - xvfb
language: python
python: 2.7
addons:
  apt:
    packages:
      - firefox-geckodriver
cache:
  directories:
  - $HOME/.pylint.d
  - eggs
  - parts/node
matrix:
  fast_finish: true
install:
- virtualenv .
- bin/pip install -r requirements.txt
- bin/buildout annotate
# FIXME:
# Avoids VersionConflict: (six 1.11.0 (/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages), Requirement.parse('six==1.10.0'))
- bin/buildout versions:six=
before_script:
  - firefox -v
script:
- bin/code-analysis
- bin/test
- bin/pylint --py3k --disable=no-absolute-import src/brasil/gov/tiles
after_success:
- pip install coverage
- coverage run bin/test --layer=\!Robot
# Coveralls
- pip install coveralls
- coveralls
# Codacy
- coverage xml
- pip install codacy-coverage
- python-codacy-coverage -r coverage.xml
notifications:
  irc: irc.freenode.org#plonegovbr
